PUT http://localhost:8080/user/addTradeHistory
Content-type: application/json

{
  "userID": 2,
  "email": null,
  "userName": null,
  "userPassword": null,
  "tradeHistories": [
    {
      "TradeHistoryID" :7,
      "purchasedPrice" : 2.3,
      "purchasedTime" : "13:99",
      "purchasedQuantities" : 10,
      "stockID" : 7
    }
  ]
}